---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list: [
    "apt",
    "java",
    "recipe[repose::filter-slf4j-http-logging]",
    "recipe[repose::filter-ip-identity]",
    "recipe[repose::filter-rate-limiting]",
    "recipe[repose::filter-header-translation]",
    "recipe[repose::service-connection-pool]",
    "recipe[repose::service-dist-datastore]",
    "recipe[repose::default]",
    "recipe[minitest-handler]"
  ]
  attributes:
    java:
      jdk_version: 7

- name: client-auth-rackspace
  run_list: [
    "recipe[repose::filter-client-auth]",
    "recipe[repose::default]",
    "recipe[minitest-handler]"
  ]
  attributes:
    repose:
      client_auth:
        auth_provider: 'RACKSPACE'

- name: client-auth-openstack
  run_list: [
    "recipe[repose::filter-client-auth]",
    "recipe[repose::default]",
    "recipe[minitest-handler]"
  ]
  attributes:
    repose:
      client_auth:
        auth_provider: 'OPENSTACK'

