---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-7.9
  driver_config:
    box: opscode-debian-7.9
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.9_chef-provisionerless.box
- name: debian-8.3
  driver_config:
    box: opscode-debian-8.3
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-8.3_chef-provisionerless.box
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
- name: centos-6.7
  driver_config:
    box: opscode-centos-6.7
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.7_chef-provisionerless.box
- name: centos-7.2
  driver_config:
    box: opscode-centos-7.2
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box


suites:
- name: default
  run_list: [
    "apt",
    "java",
    "recipe[repose::default]",
    "recipe[repose::filter-add-header]",
    "recipe[repose::filter-api-validator]",
    "recipe[repose::filter-client-auth]",
    "recipe[repose::filter-client-authorization]",
    "recipe[repose::filter-content-type-stripper]",
    "recipe[repose::filter-derp]",
    "recipe[repose::filter-header-identity]",
    "recipe[repose::filter-header-normalization]",
    "recipe[repose::filter-header-translation]",
    "recipe[repose::filter-ip-identity]",
    "recipe[repose::filter-keystone-v2]",
    "recipe[repose::filter-rackspace-auth-user]",
    "recipe[repose::filter-rate-limiting]",
    "recipe[repose::filter-slf4j-http-logging]",
    "recipe[repose::filter-translation]",
    "recipe[repose::filter-uri-identity]",
    "recipe[repose::filter-uri-stripper]",
    "recipe[repose::service-dist-datastore]",
    "recipe[repose::service-http-connection-pool]",
    "recipe[repose::service-response-messaging]"
  ]
  attributes:
    java:
      jdk_version: 7
