---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

suites:
- name: default
  run_list: [
    "apt",
    "java",
    "recipe[repose::filter-slf4j-http-logging]",
    "recipe[repose::filter-header-normalization]",
    "recipe[repose::filter-header-translation]",
    "recipe[repose::filter-header-identity]",
    "recipe[repose::filter-ip-identity]",
    "recipe[repose::filter-uri-identity]",
    "recipe[repose::filter-rackspace-auth-user]",
    "recipe[repose::filter-rate-limiting]",
    "recipe[repose::filter-translation]",
    "recipe[repose::filter-content-type-stripper]",
    "recipe[repose::service-connection-pool]",
    "recipe[repose::service-dist-datastore]",
    "recipe[repose::default]",
    "recipe[minitest-handler]"
  ]
  attributes:
    java:
      jdk_version: 7
    repose:
      client_auth:
        auth_provider: 'OPENSTACK'
      rewrite_host_header: false


- name: client-auth-rackspace
  run_list: [
    "recipe[repose::filter-client-auth]",
    "recipe[repose::default]",
    "recipe[minitest-handler]"
  ]
  attributes:
    repose:
      client_auth:
        auth_provider: 'RACKSPACE'

- name: client-auth-openstack
  run_list: [
    "recipe[repose::filter-client-auth]",
    "recipe[repose::default]",
    "recipe[minitest-handler]"
  ]
  attributes:
    repose:
      client_auth:
        auth_provider: 'OPENSTACK'

